### ISSUE TITLE
export all retrieved IDs

### ISSUE THREAD

**Issue by landroni** [basil2style/getid#4]
Please allow a context-menu button to conveniently Export all retrieved IDs to a text file on the SD card. Currently `getid` only allows copying one ID at a time, but this is not sufficiently convenient for the purposes of backing up this information. 

Having a dedicated Export button would be much more useful for backing this up.

**Comment by basil2style** [comment]
I added this feature in github and thank you for point out this feature :)

**Comment by landroni** [comment]
Thanks!
